dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.16.x

git:
  depth: 1

script:
  - export TAG=$(git describe --tags --abbrev=0)
  - echo "Tag $TAG"
  - GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -X main.Version=$TAG" -o portainer-templates-server_win_x64.exe
  - tar zcf portainer-templates-server_win_x64.tar.gz portainer-templates-server_win_x64.exe
  - GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X main.Version=$TAG" -o portainer-templates-server_linux_x64
  - tar zcf portainer-templates-server_linux_x64.tar.gz portainer-templates-server_linux_x64
  - GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w -X main.Version=$TAG" -o portainer-templates-server_osx_x64
  - tar zcf portainer-templates-server_osx_x64.tar.gz portainer-templates-server_osx_x64
  - GOOS=windows GOARCH=386 go build -ldflags "-s -w -X main.Version=$TAG" -o portainer-templates-server_win_x86.exe
  - tar zcf portainer-templates-server_win_x86.tar.gz portainer-templates-server_win_x86.exe
  - GOOS=linux GOARCH=386 go build -ldflags "-s -w -X main.Version=$TAG" -o portainer-templates-server_linux_x86
  - tar zcf portainer-templates-server_linux_x86.tar.gz portainer-templates-server_linux_x86

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "portainer-templates-server_win_x64.tar.gz"
    - "portainer-templates-server_linux_x64.tar.gz"
    - "portainer-templates-server_osx_x64.tar.gz"
    - "portainer-templates-server_win_x86.tar.gz"
    - "portainer-templates-server_linux_x86.tar.gz"
  on:
    tags: true